apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app-cert
  namespace: cert-manager
  labels:
    app: externaldns-webhook-example
spec:
  secretName: example-com-tls
  commonName: example.com
  duration: 8760h # 1y
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - "*.example.com"
  - example.com
