apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: externaldns-webhook-ca
  namespace: cert-manager
  labels:
    app: externaldns-webhook
spec:
  secretName: externaldns-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: externaldns-webhook-selfsign
  commonName: "ca.externaldns-webhook.cert-manager"
  isCA: true
