# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: externaldns-webhook-webhook-tls
  namespace: cert-manager
  labels:
    app: externaldns-webhook
spec:
  secretName: externaldns-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: externaldns-webhook-ca
  dnsNames:
  - externaldns-webhook
  - externaldns-webhook.cert-manager
  - externaldns-webhook.cert-manager.svc
  - externaldns-webhook.cert-manager.svc.cluster.local
