apiVersion: v1
kind: Service
metadata:
  name: externaldns-webhook
  namespace: cert-manager
  labels:
    app: externaldns-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: externaldns-webhook
